---
title: Teken een nieuwe achtergrond in Scratch 3
hero_image: images/banner.png
description: Hoe teken je een nieuwe Scratch 3-achtergrond
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - 
    title: Teken een nieuwe achtergrond
