---
title: एक नया Scratch 3 पृष्ठभूमि पेंट करें
hero_image: images/banner.png
description: एक नया Scratch 3 पृष्ठभूमि कैसे पेंट करें
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - title: एक नई पृष्ठभूमि पेंट करें
