---
title: Maglagay ng kulay sa bagong Scratch 3
hero_image: images/banner.png
description: Paano kulayan ang bagong Scratch 3
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - 
    title: Kulayan ang bagong backdrop
