---
title: Pinta un nuevo fondo de Scratch 3
hero_image: images/banner.png
description: Cómo pintar un nuevo fondo de Scratch 3
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - title: Pinta un nuevo fondo
