---
title: Male eine neue Scratch 3-Kulisse
hero_image: images/banner.png
description: So zeichnest du eine neue Scratch 3-Kulisse
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "Scratch"
steps:
  - title: Male eine neue Kulisse
