---
title: Desenează un nou fundal în Scratch 3
hero_image: images/banner.png
description: Cum să desenezi un fundal nou în Scratch 3
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "zgârietură"
steps:
  - title: Desenarea unui nou fundal
