---
title: Pinte um novo cenário do Scratch 3
hero_image: imagens/banner.png
description: Como pintar um novo cenário do Scratch 3
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - title: Pinte um novo cenário
