---
title: 繪製一個新的 Scratch 3 背景
hero_image: images/banner.png
description: 如何繪製新的 Scratch 3 背景
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - 
    title: Paint a new backdrop
