---
title: رسم خلفية سكراتش Scratch3 جديدة
hero_image: images/banner.png
description: كيفية رسم خلفية سكراتش Scratch3 جديدة
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - title: رسم خلفية جديدة
