---
title: 새로운 스크래치 3 배경 그리기
hero_image: images/banner.png
description: 새로운 스크래치 3 배경을 그리는 방법
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - 
    title: 새로운 배경 그리기
