---
title: Peindre un nouvel arrière-plan Scratch 3
hero_image: images/banner.png
description: Comment peindre un nouvel arrière-plan Scratch 3
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - 
    title: Peindre un nouvel arrière-plan
