---
title: නව Scratch 3 පසුබිමක්(backdrop) පින්තාරු(paint) කරන්න
hero_image: images / banner.png
description: නව Scratch 3 පසුබිමක්(backdrop) පින්තාරු(paint) කරන්නේ කෙසේද
theme: cc-ප්‍රදර්ශකය
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - 
    title: නව පසුබිමක්(backdrop) පින්තාරු(paint) කිරීම
