---
title: Scratch 3'te yeni bir dekor çizme
hero_image: images/banner.png
description: Scratch 3'te yeni bir dekor nasıl çizilir
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "scratch"
steps:
  - 
    title: Yeni bir dekor çiz
